FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY script.js /usr/share/nginx/html/script.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY words.json /usr/share/nginx/html/words.json

RUN chmod 0644 /usr/share/nginx/html/index.html \
  /usr/share/nginx/html/script.js \
  /usr/share/nginx/html/styles.css \
  /usr/share/nginx/html/words.json

EXPOSE 80
